/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SMARTCONN_LINK_STATUS_PB_H_INCLUDED
#define PB_SMARTCONN_LINK_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) smartconn_Candidate_bssid_t;
typedef struct _smartconn_Candidate {
    smartconn_Candidate_bssid_t bssid; /* 6 bytes */
    int32_t rssi; /* dBm */
    int32_t hop; /* current_hop */
} smartconn_Candidate;

typedef PB_BYTES_ARRAY_T(6) smartconn_BlackItem_bssid_t;
typedef struct _smartconn_BlackItem {
    smartconn_BlackItem_bssid_t bssid; /* 6 bytes */
} smartconn_BlackItem;

typedef struct _smartconn_Version {
    uint32_t major;
    uint32_t minor;
    uint32_t patch;
} smartconn_Version;

typedef PB_BYTES_ARRAY_T(6) smartconn_LinkStatus_mac_t;
typedef PB_BYTES_ARRAY_T(6) smartconn_LinkStatus_parent_mac_t;
typedef struct _smartconn_LinkStatus {
    smartconn_LinkStatus_mac_t mac; /* 6 */
    bool has_parent_mac;
    smartconn_LinkStatus_parent_mac_t parent_mac; /* 6 (parent_valid==1 일 때만) */
    uint32_t hop;
    int32_t rssi;
    bool has_ver;
    smartconn_Version ver;
    pb_size_t candidates_count;
    smartconn_Candidate candidates[10];
    pb_size_t blacklist_count;
    smartconn_BlackItem blacklist[10];
} smartconn_LinkStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define smartconn_Candidate_init_default         {{0, {0}}, 0, 0}
#define smartconn_BlackItem_init_default         {{0, {0}}}
#define smartconn_Version_init_default           {0, 0, 0}
#define smartconn_LinkStatus_init_default        {{0, {0}}, false, {0, {0}}, 0, 0, false, smartconn_Version_init_default, 0, {smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default, smartconn_Candidate_init_default}, 0, {smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default, smartconn_BlackItem_init_default}}
#define smartconn_Candidate_init_zero            {{0, {0}}, 0, 0}
#define smartconn_BlackItem_init_zero            {{0, {0}}}
#define smartconn_Version_init_zero              {0, 0, 0}
#define smartconn_LinkStatus_init_zero           {{0, {0}}, false, {0, {0}}, 0, 0, false, smartconn_Version_init_zero, 0, {smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero, smartconn_Candidate_init_zero}, 0, {smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero, smartconn_BlackItem_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define smartconn_Candidate_bssid_tag            1
#define smartconn_Candidate_rssi_tag             2
#define smartconn_Candidate_hop_tag              3
#define smartconn_BlackItem_bssid_tag            1
#define smartconn_Version_major_tag              1
#define smartconn_Version_minor_tag              2
#define smartconn_Version_patch_tag              3
#define smartconn_LinkStatus_mac_tag             1
#define smartconn_LinkStatus_parent_mac_tag      2
#define smartconn_LinkStatus_hop_tag             3
#define smartconn_LinkStatus_rssi_tag            4
#define smartconn_LinkStatus_ver_tag             5
#define smartconn_LinkStatus_candidates_tag      6
#define smartconn_LinkStatus_blacklist_tag       7

/* Struct field encoding specification for nanopb */
#define smartconn_Candidate_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    bssid,             1) \
X(a, STATIC,   REQUIRED, SINT32,   rssi,              2) \
X(a, STATIC,   REQUIRED, SINT32,   hop,               3)
#define smartconn_Candidate_CALLBACK NULL
#define smartconn_Candidate_DEFAULT NULL

#define smartconn_BlackItem_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    bssid,             1)
#define smartconn_BlackItem_CALLBACK NULL
#define smartconn_BlackItem_DEFAULT NULL

#define smartconn_Version_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   major,             1) \
X(a, STATIC,   REQUIRED, UINT32,   minor,             2) \
X(a, STATIC,   REQUIRED, UINT32,   patch,             3)
#define smartconn_Version_CALLBACK NULL
#define smartconn_Version_DEFAULT NULL

#define smartconn_LinkStatus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    mac,               1) \
X(a, STATIC,   OPTIONAL, BYTES,    parent_mac,        2) \
X(a, STATIC,   REQUIRED, UINT32,   hop,               3) \
X(a, STATIC,   REQUIRED, SINT32,   rssi,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ver,               5) \
X(a, STATIC,   REPEATED, MESSAGE,  candidates,        6) \
X(a, STATIC,   REPEATED, MESSAGE,  blacklist,         7)
#define smartconn_LinkStatus_CALLBACK NULL
#define smartconn_LinkStatus_DEFAULT NULL
#define smartconn_LinkStatus_ver_MSGTYPE smartconn_Version
#define smartconn_LinkStatus_candidates_MSGTYPE smartconn_Candidate
#define smartconn_LinkStatus_blacklist_MSGTYPE smartconn_BlackItem

extern const pb_msgdesc_t smartconn_Candidate_msg;
extern const pb_msgdesc_t smartconn_BlackItem_msg;
extern const pb_msgdesc_t smartconn_Version_msg;
extern const pb_msgdesc_t smartconn_LinkStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define smartconn_Candidate_fields &smartconn_Candidate_msg
#define smartconn_BlackItem_fields &smartconn_BlackItem_msg
#define smartconn_Version_fields &smartconn_Version_msg
#define smartconn_LinkStatus_fields &smartconn_LinkStatus_msg

/* Maximum encoded size of messages (where known) */
#define SMARTCONN_LINK_STATUS_PB_H_MAX_SIZE      smartconn_LinkStatus_size
#define smartconn_BlackItem_size                 8
#define smartconn_Candidate_size                 20
#define smartconn_LinkStatus_size                368
#define smartconn_Version_size                   18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
