/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "link_status.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smartconn_Candidate, smartconn_Candidate, AUTO)


PB_BIND(smartconn_BlackItem, smartconn_BlackItem, AUTO)


PB_BIND(smartconn_Version, smartconn_Version, AUTO)


PB_BIND(smartconn_LinkStatus, smartconn_LinkStatus, 2)



